# Generated by Django 3.0.4 on 2020-03-17 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date and time'),
        ),
    ]
