# Generated by Django 3.0.4 on 2020-03-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='content',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title',
        ),
        migrations.AddField(
            model_name='idea',
            name='content_de',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Deutsch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_en_gb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (British English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_en_us',
            field=models.TextField(db_tablespace='', default='content en_us', verbose_name='Content (US English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='content_fr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Français)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_lt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Lietuvių kalba)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_pt_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Português)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_de',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Deutsch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_en_gb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (British English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_en_us',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (US English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_fr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Français)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_lt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Lietuvių kalba)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_pt_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Português)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_de',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Deutsch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_en_gb',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (British English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_en_us',
            field=models.CharField(db_tablespace='', default='title en_us', max_length=200, verbose_name='Title (US English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='title_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Français)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_lt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Lietuvių kalba)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_pt_br',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Português)'),
        ),
    ]
