# Generated by Django 3.0.4 on 2020-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_auto_20200324_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='content_itemprop',
            field=models.TextField(blank=True, choices=[('ACCESS_MODE', 'accessMode'), ('ALTERNATE_NAME', 'alternateName'), ('BOOK_EDITION', 'bookEdition'), ('DESCRIPTION', 'description'), ('HEADLINE', 'headline')], default='', max_length=200, verbose_name='Content microdata item property'),
        ),
        migrations.AddField(
            model_name='idea',
            name='itemtype',
            field=models.CharField(blank=True, choices=[('THING', 'Thing'), ('CREATIVE_WORK', 'CreativeWork'), ('BOOK', 'Book')], max_length=100, verbose_name='Microdata item type'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_itemprop',
            field=models.CharField(blank=True, choices=[('ACCESS_MODE', 'accessMode'), ('ALTERNATE_NAME', 'alternateName'), ('BOOK_EDITION', 'bookEdition'), ('DESCRIPTION', 'description'), ('HEADLINE', 'headline')], default='', max_length=200, verbose_name='Title microdata item property'),
        ),
    ]
