# Generated by Django 3.0.4 on 2020-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_auto_20200330_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='demo_app.Category', verbose_name='Category'),
        ),
    ]
