# Generated by Django 3.0.4 on 2020-03-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    def copy_categories(apps, schema_editor):
        Idea = apps.get_model("demo_app", "Idea")
        for idea in Idea.objects.all():
            if idea.category:
                idea.categories.add(idea.category)
                idea.save()

    dependencies = [
        ('demo_app', '0008_idea_categories'),
    ]

    operations = [
        migrations.RunPython(copy_categories),
    ]
