# Generated by Django 3.0.4 on 2020-03-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0009_copy_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
    ]
