# Generated by Django 3.0.4 on 2020-03-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0010_remove_idea_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='content_en_us',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='description_en_us',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_en_us',
        ),
        migrations.AddField(
            model_name='idea',
            name='content_af',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Afrikaans)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ar',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Arabic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ast',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Asturian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_az',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Azerbaijani)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_be',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Belarusian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_bg',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Bulgarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_bn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Bengali)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Breton)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_bs',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Bosnian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ca',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Catalan)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_cs',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Czech)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_cy',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Welsh)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_da',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Danish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_dsb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Lower Sorbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_el',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Greek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_en',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_en_au',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Australian English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_eo',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Esperanto)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_es',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_es_ar',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Argentinian Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_es_co',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Colombian Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_es_mx',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Mexican Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_es_ni',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Nicaraguan Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_es_ve',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Venezuelan Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_et',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Estonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_eu',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Basque)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_fa',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Persian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_fi',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Finnish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_fy',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Frisian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ga',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Irish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_gd',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Scottish Gaelic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_gl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Galician)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_he',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Hebrew)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_hi',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Hindi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_hr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Croatian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_hsb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Upper Sorbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_hu',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Hungarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_hy',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Armenian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ia',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Interlingua)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_id',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Indonesian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_io',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Ido)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_is',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Icelandic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_it',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Italian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ja',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Japanese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ka',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Georgian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_kab',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Kabyle)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_kk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Kazakh)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_km',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Khmer)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_kn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Kannada)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ko',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Korean)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_lb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Luxembourgish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_lv',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Latvian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_mk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Macedonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ml',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Malayalam)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_mn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Mongolian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_mr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Marathi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_my',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Burmese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_nb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Norwegian Bokmål)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ne',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Nepali)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_nl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Dutch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_nn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Norwegian Nynorsk)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_os',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Ossetic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_pa',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Punjabi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_pl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Polish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_pt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Portuguese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ro',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Romanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ru',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Russian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Slovak)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Slovenian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sq',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Albanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Serbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sr_latn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Serbian Latin)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sv',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Swedish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sw',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Swahili)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ta',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Tamil)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_te',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Telugu)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_th',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Thai)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_tr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Turkish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_tt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Tatar)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_udm',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Udmurt)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_uk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ur',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Urdu)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_uz',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Uzbek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_vi',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Vietnamese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_zh_hans',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Simplified Chinese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_zh_hant',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Traditional Chinese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_af',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Afrikaans)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ar',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ast',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Asturian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_az',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Azerbaijani)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_be',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Belarusian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_bg',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Bulgarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_bn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Bengali)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Breton)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_bs',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Bosnian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ca',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Catalan)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_cs',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Czech)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_cy',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Welsh)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_da',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Danish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_dsb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Lower Sorbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_el',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Greek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_en',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_en_au',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Australian English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_eo',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Esperanto)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_es',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_es_ar',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Argentinian Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_es_co',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Colombian Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_es_mx',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Mexican Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_es_ni',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Nicaraguan Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_es_ve',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Venezuelan Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_et',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Estonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_eu',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Basque)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_fa',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Persian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_fi',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Finnish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_fy',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Frisian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ga',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Irish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_gd',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Scottish Gaelic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_gl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Galician)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_he',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Hebrew)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_hi',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_hr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Croatian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_hsb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Upper Sorbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_hu',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Hungarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_hy',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ia',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Interlingua)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_id',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Indonesian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_io',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Ido)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_is',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Icelandic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_it',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Italian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ja',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Japanese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ka',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Georgian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_kab',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Kabyle)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_kk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Kazakh)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_km',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Khmer)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_kn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Kannada)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ko',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Korean)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_lb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Luxembourgish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_lv',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Latvian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_mk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Macedonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ml',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Malayalam)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_mn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Mongolian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_mr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Marathi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_my',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Burmese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_nb',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Norwegian Bokmål)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ne',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Nepali)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_nl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Dutch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_nn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Norwegian Nynorsk)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_os',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Ossetic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_pa',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Punjabi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_pl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Polish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_pt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Portuguese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ro',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Romanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ru',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_sk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Slovak)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_sl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Slovenian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_sq',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Albanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_sr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Serbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_sr_latn',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Serbian Latin)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_sv',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Swedish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_sw',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Swahili)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ta',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Tamil)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_te',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Telugu)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_th',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Thai)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_tr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Turkish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_tt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Tatar)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_udm',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Udmurt)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_uk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_ur',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Urdu)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_uz',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Uzbek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_vi',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Vietnamese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_zh_hans',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Simplified Chinese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_zh_hant',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Traditional Chinese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_af',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Afrikaans)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ar',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ast',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Asturian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_az',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Azerbaijani)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_be',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Belarusian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_bg',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Bulgarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_bn',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Bengali)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_br',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Breton)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_bs',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Bosnian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ca',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Catalan)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_cs',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Czech)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_cy',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Welsh)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_da',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Danish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_dsb',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Lower Sorbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_el',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Greek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_en_au',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Australian English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_eo',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Esperanto)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_es_ar',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Argentinian Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_es_co',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Colombian Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_es_mx',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Mexican Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_es_ni',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Nicaraguan Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_es_ve',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Venezuelan Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_et',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Estonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_eu',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Basque)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_fa',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Persian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_fi',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Finnish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_fy',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Frisian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ga',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Irish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_gd',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Scottish Gaelic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_gl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Galician)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_he',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Hebrew)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_hi',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_hr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Croatian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_hsb',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Upper Sorbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_hu',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Hungarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_hy',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Armenian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ia',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Interlingua)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_id',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Indonesian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_io',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Ido)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_is',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Icelandic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_it',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Italian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ja',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Japanese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ka',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Georgian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_kab',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Kabyle)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_kk',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Kazakh)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_km',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Khmer)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_kn',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Kannada)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ko',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Korean)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_lb',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Luxembourgish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_lv',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Latvian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_mk',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Macedonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ml',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Malayalam)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_mn',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Mongolian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_mr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Marathi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_my',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Burmese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_nb',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Norwegian Bokmål)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ne',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Nepali)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_nl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Dutch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_nn',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Norwegian Nynorsk)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_os',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Ossetic)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_pa',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Punjabi)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_pl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Polish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Portuguese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ro',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Romanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ru',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sk',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovak)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovenian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sq',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Albanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Serbian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sr_latn',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Serbian Latin)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sv',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Swedish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sw',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Swahili)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ta',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Tamil)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_te',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Telugu)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_th',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Thai)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_tr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Turkish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_tt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Tatar)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_udm',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Udmurt)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_uk',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ur',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Urdu)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_uz',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Uzbek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_vi',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Vietnamese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Simplified Chinese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Traditional Chinese)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content_de',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (German)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content_fr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (French)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content_lt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Lithuanian)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content_pt_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Brazilian Portuguese)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description_de',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (German)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description_fr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (French)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description_lt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Lithuanian)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description_pt_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Brazilian Portuguese)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title_de',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (French)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title_lt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Lithuanian)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title_pt_br',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Brazilian Portuguese)'),
        ),
    ]
