# Generated by Django 3.0.4 on 2020-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0012_auto_20200331_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='content_pt_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Português)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_pt_br',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Description (Português)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_pt_br',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Português)'),
        ),
    ]
